FROM fluent/fluentd:v1.12.1-1.0

USER root

# Add extra certificates. Specifically, rapidssl is needed because it's used
# by Papertrail.
ENV LOCAL_TRUST_DIR /usr/local/share/ca-certificates
COPY rapidssl.crt "$LOCAL_TRUST_DIR/rapidssl.crt"
RUN update-ca-certificates

# The Redis output is used with a local Redis, so we need to install it. We
# also pull coreutils, largely for convenience in our tests.
RUN apk add --no-cache coreutils redis curl bash openssl

# Now, we need to install stunnel. It's only in the edge repo, and that package
# often breaks, so we install from source.
# TODO: This breaks on libssl1.0 so punting for now
# COPY bin/install-stunnel.sh /usr/bin/install-stunnel.sh
# RUN /usr/bin/install-stunnel.sh

# Install the necessary plugins
RUN apk add --no-cache --update --virtual .build-deps \
      build-base ruby-dev \
      && gem install fluent-plugin-logdna \
      && gem install fluent-plugin-papertrail \
      && gem install fluent-plugin-elasticsearch \
      && gem install fluent-plugin-sumologic_output \
      && gem install fluent-plugin-beats --no-document \
      && gem install fluent-plugin-syslog_rfc5424 \
      && gem install fluent-plugin-datadog \
      && gem sources --clear-all \
      && apk del .build-deps \
      && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

COPY templates/stunnel.conf /stunnel.conf
COPY templates/redis.conf.erb /redis.conf.erb
COPY templates/load-message.lua /load-message.lua
COPY templates/fluent.conf.erb /fluent.conf.erb
COPY bin/run-gentleman-jerry.sh run-gentleman-jerry.sh

# Install BATS (for tests)
RUN curl -sL https://github.com/sstephenson/bats/archive/master.zip > /tmp/bats.zip \
    && cd /tmp \
    && unzip -q bats.zip \
    && ./bats-master/install.sh /usr/local \
    # /usr/local/bin/bats should be a symlink, so make it happen.
    && ln -sf /usr/local/libexec/bats /usr/local/bin/bats \
    && rm -rf /tmp/bats*

# Run tests
COPY test /tmp/test
# TODO: Run this once the tests are updated
# RUN /tmp/test/run_tests.sh

# A volume containing a certificate pair named jerry.key/jerry.crt must be mounted into
# this directory on the container.
VOLUME ["/tmp/certs"]

# Lumberjack
EXPOSE 5000
# Redis (used if the drain is a tail)
EXPOSE 6000

CMD ["/bin/bash", "run-gentleman-jerry.sh"]
